/*
 * Backend RESTful APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: randy@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImageControllerApi
 */
@Ignore
public class ImageControllerApiTest {

    private final ImageControllerApi api = new ImageControllerApi();

    
    /**
     * download
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void downloadUsingGETTest() throws ApiException {
        Integer id = null;
        String response = api.downloadUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * uploadTest3
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadTest3UsingPOSTTest() throws ApiException {
        File file = null;
        byte[] content = null;
        String flag = null;
        String processInstanceId = null;
        Integer id = null;
        String targetId = null;
        String fileName = null;
        String extension = null;
        File file2 = null;
        String purpose = null;
        String attribute = null;
        String response = api.uploadTest3UsingPOST(file, content, flag, processInstanceId, id, targetId, fileName, extension, file2, purpose, attribute);

        // TODO: test validations
    }
    
    /**
     * uploadTest4
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadTest4UsingPOSTTest() throws ApiException {
        byte[] content = null;
        String flag = null;
        String processInstanceId = null;
        Integer id = null;
        String targetId = null;
        String fileName = null;
        String extension = null;
        File file = null;
        String purpose = null;
        String attribute = null;
        String response = api.uploadTest4UsingPOST(content, flag, processInstanceId, id, targetId, fileName, extension, file, purpose, attribute);

        // TODO: test validations
    }
    
}
